/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as OpinioniRouteImport } from './routes/opinioni'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PreventivoRouteImport } from './routes/preventivo'
import { Route as PromozioniRouteImport } from './routes/promozioni'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as SostenibilitaRouteImport } from './routes/sostenibilita'
import { Route as ChiSonoIndexRouteImport } from './routes/chi-sono.index'
import { Route as ChiSonoFaqRouteImport } from './routes/chi-sono.faq'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as ServiziIndexRouteImport } from './routes/servizi.index'
import { Route as ServiziSlugRouteImport } from './routes/servizi.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinioniRoute = OpinioniRouteImport.update({
  id: '/opinioni',
  path: '/opinioni',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivoRoute = PreventivoRouteImport.update({
  id: '/preventivo',
  path: '/preventivo',
  getParentRoute: () => rootRouteImport,
} as any)
const PromozioniRoute = PromozioniRouteImport.update({
  id: '/promozioni',
  path: '/promozioni',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const SostenibilitaRoute = SostenibilitaRouteImport.update({
  id: '/sostenibilita',
  path: '/sostenibilita',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoIndexRoute = ChiSonoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChiSonoRoute,
} as any)
const ChiSonoFaqRoute = ChiSonoFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => ChiSonoRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortfolioRoute,
} as any)
const ServiziIndexRoute = ServiziIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiziRoute,
} as any)
const ServiziSlugRoute = ServiziSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiziRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-sono': typeof ChiSonoRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/opinioni': typeof OpinioniRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/preventivo': typeof PreventivoRoute
  '/promozioni': typeof PromozioniRoute
  '/servizi': typeof ServiziRouteWithChildren
  '/sostenibilita': typeof SostenibilitaRoute
  '/chi-sono/faq': typeof ChiSonoFaqRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/servizi/$slug': typeof ServiziSlugRoute
  '/chi-sono/': typeof ChiSonoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/servizi/': typeof ServiziIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/opinioni': typeof OpinioniRoute
  '/preventivo': typeof PreventivoRoute
  '/promozioni': typeof PromozioniRoute
  '/sostenibilita': typeof SostenibilitaRoute
  '/chi-sono/faq': typeof ChiSonoFaqRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/servizi/$slug': typeof ServiziSlugRoute
  '/chi-sono': typeof ChiSonoIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/servizi': typeof ServiziIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-sono': typeof ChiSonoRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/opinioni': typeof OpinioniRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/preventivo': typeof PreventivoRoute
  '/promozioni': typeof PromozioniRoute
  '/servizi': typeof ServiziRouteWithChildren
  '/sostenibilita': typeof SostenibilitaRoute
  '/chi-sono/faq': typeof ChiSonoFaqRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/servizi/$slug': typeof ServiziSlugRoute
  '/chi-sono/': typeof ChiSonoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/servizi/': typeof ServiziIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-sono'
    | '/contatti'
    | '/opinioni'
    | '/portfolio'
    | '/preventivo'
    | '/promozioni'
    | '/servizi'
    | '/sostenibilita'
    | '/chi-sono/faq'
    | '/portfolio/$slug'
    | '/servizi/$slug'
    | '/chi-sono/'
    | '/portfolio/'
    | '/servizi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/opinioni'
    | '/preventivo'
    | '/promozioni'
    | '/sostenibilita'
    | '/chi-sono/faq'
    | '/portfolio/$slug'
    | '/servizi/$slug'
    | '/chi-sono'
    | '/portfolio'
    | '/servizi'
  id:
    | '__root__'
    | '/'
    | '/chi-sono'
    | '/contatti'
    | '/opinioni'
    | '/portfolio'
    | '/preventivo'
    | '/promozioni'
    | '/servizi'
    | '/sostenibilita'
    | '/chi-sono/faq'
    | '/portfolio/$slug'
    | '/servizi/$slug'
    | '/chi-sono/'
    | '/portfolio/'
    | '/servizi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSonoRoute: typeof ChiSonoRouteWithChildren
  ContattiRoute: typeof ContattiRoute
  OpinioniRoute: typeof OpinioniRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PreventivoRoute: typeof PreventivoRoute
  PromozioniRoute: typeof PromozioniRoute
  ServiziRoute: typeof ServiziRouteWithChildren
  SostenibilitaRoute: typeof SostenibilitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinioni': {
      id: '/opinioni'
      path: '/opinioni'
      fullPath: '/opinioni'
      preLoaderRoute: typeof OpinioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivo': {
      id: '/preventivo'
      path: '/preventivo'
      fullPath: '/preventivo'
      preLoaderRoute: typeof PreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promozioni': {
      id: '/promozioni'
      path: '/promozioni'
      fullPath: '/promozioni'
      preLoaderRoute: typeof PromozioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sostenibilita': {
      id: '/sostenibilita'
      path: '/sostenibilita'
      fullPath: '/sostenibilita'
      preLoaderRoute: typeof SostenibilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono/': {
      id: '/chi-sono/'
      path: '/'
      fullPath: '/chi-sono/'
      preLoaderRoute: typeof ChiSonoIndexRouteImport
      parentRoute: typeof ChiSonoRoute
    }
    '/chi-sono/faq': {
      id: '/chi-sono/faq'
      path: '/faq'
      fullPath: '/chi-sono/faq'
      preLoaderRoute: typeof ChiSonoFaqRouteImport
      parentRoute: typeof ChiSonoRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/servizi/': {
      id: '/servizi/'
      path: '/'
      fullPath: '/servizi/'
      preLoaderRoute: typeof ServiziIndexRouteImport
      parentRoute: typeof ServiziRoute
    }
    '/servizi/$slug': {
      id: '/servizi/$slug'
      path: '/$slug'
      fullPath: '/servizi/$slug'
      preLoaderRoute: typeof ServiziSlugRouteImport
      parentRoute: typeof ServiziRoute
    }
  }
}

interface ChiSonoRouteChildren {
  ChiSonoFaqRoute: typeof ChiSonoFaqRoute
  ChiSonoIndexRoute: typeof ChiSonoIndexRoute
}

const ChiSonoRouteChildren: ChiSonoRouteChildren = {
  ChiSonoFaqRoute: ChiSonoFaqRoute,
  ChiSonoIndexRoute: ChiSonoIndexRoute,
}

const ChiSonoRouteWithChildren =
  ChiSonoRoute._addFileChildren(ChiSonoRouteChildren)

interface PortfolioRouteChildren {
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioSlugRoute: PortfolioSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

interface ServiziRouteChildren {
  ServiziSlugRoute: typeof ServiziSlugRoute
  ServiziIndexRoute: typeof ServiziIndexRoute
}

const ServiziRouteChildren: ServiziRouteChildren = {
  ServiziSlugRoute: ServiziSlugRoute,
  ServiziIndexRoute: ServiziIndexRoute,
}

const ServiziRouteWithChildren =
  ServiziRoute._addFileChildren(ServiziRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSonoRoute: ChiSonoRouteWithChildren,
  ContattiRoute: ContattiRoute,
  OpinioniRoute: OpinioniRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PreventivoRoute: PreventivoRoute,
  PromozioniRoute: PromozioniRoute,
  ServiziRoute: ServiziRouteWithChildren,
  SostenibilitaRoute: SostenibilitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
